force-app/main/default/objects/Process__c/Process__c.object-meta.xml
<CustomObject>
    <description>Represents a business process.</description>
    <label>Process</label>
    <nameField>
        <label>Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProcessStage__c/ProcessStage__c.object-meta.xml
<CustomObject>
    <description>A stage in the process.</description>
    <label>Process Stage</label>
    <nameField>
        <label>Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProcessStage__c/fields/ProcessRef__c.field-meta.xml
<CustomField>
    <fullName>ProcessRef__c</fullName>
    <label>Process</label>
    <referenceTo>Process__c</referenceTo>
    <relationshipLabel>Process Stages</relationshipLabel>
    <relationshipName>Process_Stages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TaskDefinition__c/TaskDefinition__c.object-meta.xml
<CustomObject>
    <description>The definition of a task in a stage. It could be a subtask too.</description>
    <label>Task Definition</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Definitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskDefinition__c/fields/CompletionFormula__c.field-meta.xml
<CustomField>
    <fullName>CompletionFormula__c</fullName>
    <label>Completion Formula</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TaskDefinition__c/fields/StageRef__c.field-meta.xml
<CustomField>
    <fullName>StageRef__c</fullName>
    <label>Process Stage</label>
    <referenceTo>ProcessStage__c</referenceTo>
    <relationshipLabel>Task Definitions</relationshipLabel>
    <relationshipName>TaskDefinitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TaskTriggerHandlerTest.cls
/**
 * Test class for the TaskTriggerHandler class
 */
@IsTest
public with sharing class TaskTriggerHandlerTest {
    @TestSetup
    static void setup(){
        Process__c process = new Process__c(
            Name = 'Test Process'
        );
        insert process;

        ProcessStage__c stage = new ProcessStage__c(
            Name = 'Test Stage',
            ProcessRef__c = process.Id
        );
        insert stage;

        TaskDefinition__c taskDefinition = new TaskDefinition__c(
            Name = 'Test Task Definition',
            StageRef__c = stage.Id,
            CompletionFormula__c = 'true'
        );
        insert taskDefinition;
    }

    @IsTest
    static void testOnAfterUpdateCompleteTask() {
        Process__c process = [SELECT Id FROM Process__c LIMIT 1];
        TaskDefinition__c taskDefinition = [SELECT Id FROM TaskDefinition__c LIMIT 1];

        Task task = new Task(
            WhatId = process.Id,
            Subject = 'Test Task',
            TaskDefinitionRef__c = taskDefinition.Id
        );
        insert task;

        Test.startTest();
        task.Description = 'Testing the update';
        update task;
        Test.stopTest();

        task = [SELECT Id, Status FROM Task WHERE Id = :task.Id];

        Assert.areEqual('Completed', task.Status, 'Should be completed');
    }

    @IsTest
    static void testOnAfterUpdateIncompleteTask() {
        Process__c process = [SELECT Id FROM Process__c LIMIT 1];
        TaskDefinition__c taskDefinition = [SELECT Id FROM TaskDefinition__c LIMIT 1];
        taskDefinition.CompletionFormula__c = 'false';
        update taskDefinition;

        Task task = new Task(
            WhatId = process.Id,
            Subject = 'Test Task',
            TaskDefinitionRef__c = taskDefinition.Id
        );
        insert task;

        Test.startTest();
        task.Description = 'Testing the update';
        update task;
        Test.stopTest();

        task = [SELECT Id, Status FROM Task WHERE Id = :task.Id];

        Assert.areNotEqual('Completed', task.Status, 'Should not be completed');
    }

    @IsTest
    static void testOnAfterUpdateCompleteMultipleTasks() {
        Process__c process = [SELECT Id FROM Process__c LIMIT 1];
        TaskDefinition__c taskDefinition = [SELECT Id FROM TaskDefinition__c LIMIT 1];
        List<Task> tasks = new List<Task>();

        for (Integer i = 0; i < 10; i++) {
            Task task = new Task(
                WhatId = process.Id,
                Subject = 'Test Task ' + i,
                TaskDefinitionRef__c = taskDefinition.Id
            );
            tasks.add(task);
        }

        insert tasks;

        for (Task t : tasks) {
            t.Description = 'Testing the update';
        }

        Test.startTest();
        update tasks;
        Test.stopTest();

        tasks = [SELECT Id, Status FROM Task WHERE Id IN :tasks];

        for (Task t : tasks) {
            Assert.areEqual('Completed', t.Status, 'Should be completed');
        }
    }
}