force-app/main/default/objects/ProcessStage__c/ProcessStage__c.object-meta.xml
<CustomObject>
    <description>A stage in the process.</description>
    <label>Process Stage</label>
    <nameField>
        <label>Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProcessStage__c/fields/ProcessRef__c.field-meta.xml
<CustomField>
    <fullName>ProcessRef__c</fullName>
    <label>Process</label>
    <referenceTo>Process__c</referenceTo>
    <relationshipLabel>Process Stages</relationshipLabel>
    <relationshipName>Process_Stages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TaskDefinition__c/TaskDefinition__c.object-meta.xml
<CustomObject>
    <description>The definition of a task in a stage. It could be a subtask too.</description>
    <label>Task Definition</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Definitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskDefinition__c/fields/CompletionFormula__c.field-meta.xml
<CustomField>
    <fullName>CompletionFormula__c</fullName>
    <label>Completion Formula</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TaskDefinition__c/fields/StageRef__c.field-meta.xml
<CustomField>
    <fullName>StageRef__c</fullName>
    <label>Process Stage</label>
    <referenceTo>ProcessStage__c</referenceTo>
    <relationshipLabel>Task Definitions</relationshipLabel>
    <relationshipName>TaskDefinitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TaskTriggerHandler.cls
public with sharing class TaskTriggerHandler {
    public static void onAfterUpdate(List<Task> newTasks, Map<Id, Task> oldTasks) {
        List<Task> processableTasks = new List<Task>();

        for (Task t : newTasks) {
            if (t.Status == 'Completed') {
                continue;
            }

            if (String.isNotBlank(t.TaskDefinitionRef__c)) {
                processableTasks.add(t);
            }
        }

        process(processableTasks);
    }

    /**
     * @description Process the tasks
     * @param tasks The tasks to process
     */
    private static void process(List<Task> tasks) {
        Set<Id> taskDefinitionIds = new Set<Id>();

        for (Task t : tasks) {
            taskDefinitionIds.add(t.TaskDefinitionRef__c);
        }

        Map<Id, TaskDefinition__c> taskDefinitions = new Map<Id, TaskDefinition__c>([
            SELECT Id, Name, StageRef__r.ProcessRef__c, StageRef__c, CompletionFormula__c
            FROM TaskDefinition__c
            WHERE Id IN :taskDefinitionIds
        ]);

        Schema.SObjectType taskSobjectType = Schema.Task.getSObjectType();
        Map<Id, FormulaEval.FormulaInstance> formulaInstances = new Map<Id, FormulaEval.FormulaInstance>();

        for (TaskDefinition__c td : taskDefinitions.values()) {
            // Build the formula for each
            FormulaEval.FormulaInstance ff = Formula.builder()
                .withType(taskSobjectType)
                .withReturnType(FormulaEval.FormulaReturnType.BOOLEAN)
                .withFormula(td.CompletionFormula__c)
                // .parseAsTemplate(false)
                .build();

            formulaInstances.put(td.Id, ff);
        }

        List<Task> tasksToUpdate = new List<Task>();

        for (Task t : tasks) {
            if (!formulaInstances.containsKey(t.TaskDefinitionRef__c)) {
                continue;
            }

            FormulaEval.FormulaInstance ff = formulaInstances.get(t.TaskDefinitionRef__c);

            if (!Boolean.valueOf(ff.evaluate(t))) {
                continue;
            }

            Task copy = new Task(Id = t.Id);
            // set task fields
            copy.Status = 'Completed';
            tasksToUpdate.add(copy);
        }

        System.enqueueJob(new TaskCompletionHandlerQueueable(tasksToUpdate));
    }
}